### ISSUE TITLE
I can't make it work, receiving "pluginIsDisabled" error.

### ISSUE THREAD

**Issue by mgkaradag** [bluedesign/speech-recognition-feat-siri#22]
Although, I have done the iOS Quirks, Xcode project settings and listen for the `deviceready`event first before using the plug-in, I cannot make it work on iOS10.2. It gives "pluginIsDisabled" error. 

Can it be related with requesting access to Siri service as well (via `NSSiriUsageDescription`etc.) ?

**Comment by rajeshpdurai16** [comment]
Any solution for this bug? I am also struggling with the same issue.

**Comment by ochakov** [comment]
I had the same problem and it caused by having a dash in the executable (main folder) name

**Comment by bluedesign** [comment]
Hi, ochakov
Please tell me the version of the Node.js you are setting up

**Comment by ochakov** [comment]
The version of Node.js on my Mac is 8.9.1, but the problem was not related to Node, but to the Cordova library itself.
Check this code [here](https://github.com/apache/cordova-ios/blob/a5e2fbaaa4d3e75e6cf10135569e58826dc29d47/CordovaLib/Classes/Public/CDVViewController.m#L656) and it is unable to find a Swift class if the CFBundleExecutable has dash inside. I renamed the project and the now it's working.
