### ISSUE TITLE
Error while building project

### ISSUE THREAD

**Issue by sam617** [bluedesign/speech-recognition-feat-siri#4]
Hi bluedesign,

I am trying to use your plugin in one of my cordova project for ios, but when I try to build it using cordova it gives me the following error.

**Environment:**

cordova: 6.4
cordova ios: 4.3

Xcode: 8.
Swift Compiler version: 3

iOS device: iPad mini 4

**Error :**
![image](https://cloud.githubusercontent.com/assets/24840336/21563770/5a8cc94c-ceab-11e6-83fb-ec8ab6878c3c.png)

**Comment by bluedesign** [comment]
hi, sam617
Thank you for the report.
I also confirmed that the same error occurred when I made it the same environment as you
However, this problem can not be solved yet.
because in my development environment Apache Cordova's version upgrade (v6.3.1 -> 6.4.0) does not work.

So I have a question
Could you tell me the version of npm, node in your development environment.

For your reference, my development environment looks like this
If this combination is working normally

Apache Cordova : 6.3.1
cordova ios : 4.2.1
xcode : 8.2.1(8C1002)

node : v0.12.0
npm : 2.5.1

**Comment by bluedesign** [comment]
hi, sam617
I improved the development environment and verification environment and retried.
Refactoring was done.
Please try again with v2.0.2

**Comment by sam617** [comment]
Hi bluedesign,

Thanks for your reply but I am still getting the same error.
My development environment looks like this:
Xcode : 8.1
Node.js : v7.2
npm : 3.1
Apache Cordova : 6.4.0
cordova ios : 4.3.1
![2017-01-02](https://cloud.githubusercontent.com/assets/24840336/21587755/b9cca1aa-d105-11e6-8a89-3067d59e0f94.png)

**Comment by bluedesign** [comment]
I can not downgrade and verify Xcode and npm.

[My Development and verification environment ]
Xcode : 8.2.1(8C1002, swift compiler uses the latest version included in Xcode)
Node.js : v6.9.2
npm : 4.0.5
Apache Cordova : 6.4.0
cordova ios : 4.3.1

Incidentally, 
It seems that the version of npm is lower than the version of Node.js, but is it consistent?
Will npm upgrade after installing node
Or is it impossible to upgrade the version of npm with limitations of other projects?

**Comment by sam617** [comment]
HI Blueddesign,

I updated the xcode to 8.2 at first few attempts it gave me errors but now it working perfectly fine.
Thanks a lot for your help.
